# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35c7b971ccc5a5a84a1a5007f4fe974ff2da2ef0c957b3e997d62412a939bcdba295d74b76ac71b0b0090f23ccea159d07677c13778ca5abd833c5cd5ec27528

test:
  secret_key_base: 5eb1b51ff807ac529368cc11f998a9c5ddf46b7ad5c39a918d4d5bee780818d6289378253e298ae583337485b2aa3e0af150267f4452cc63a7da030f53dc6a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
