class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  #Below is a list of curse words taken from GOOGLE'S banned words list!
  FORBIDDEN_USERNAMES = ["4r5e",
        "5h1t",
        "5hit",
        "a55",
        "anal",
        "ar5e",
        "arrse",
        "ass-fucker",
        "asses",
        "assfucker",
        "assfukka",
        "asshole",
        "assholes",
        "asswhole",
        "b17ch",
        "b1tch",
        "ballbag",
        "ballsack",
        "bastard",
        "beastiality",
        "bestiality",
        "biatch",
        "bitch",
        "bitcher",
        "bitchers",
        "bitches",
        "bitchin",
        "bitching",
        "blowjob",
        "blowjob",
        "blowjobs",
        "boiolas",
        "bollock",
        "bollok",
        "boob",
        "boobs",
        "booobs",
        "boooobs",
        "booooobs",
        "booooooobs",
        "bunnyfucker",
        "butthole",
        "buttmuch",
        "buttplug",
        "c0ck",
        "c0cksucker",
        "carpetmuncher",
        "chink",
        "cl1t",
        "clit",
        "clitoris",
        "cocksucker",
        "cockface",
        "cockhead",
        "cockmunch",
        "cockmuncher",
        "cocksuck",
        "cocksucked",
        "cocksucker",
        "cocksucking",
        "cocksucks",
        "cocksuka",
        "cocksukka",
        "cokmuncher",
        "coksucka",
        "cumming",
        "cumshot",
        "cunilingus",
        "cunillingus",
        "cunnilingus",
        "cuntlick",
        "cuntlicker",
        "cuntlicking",
        "cunt",
        "cyberfuc",
        "cyberfuck",
        "cyberfucked",
        "cyberfucker",
        "cyberfuckers",
        "cyberfucking",
        "d1ck",
        "dickhead",
        "dildo",
        "dildos",
        "dlck",
        "dog-fucker",
        "donkeyribber",
        "ejaculate",
        "ejaculated",
        "ejaculates",
        "ejaculating",
        "ejaculatings",
        "ejaculation",
        "ejakulate",
        "f4nny",
        "fag",
        "fagging",
        "faggitt",
        "faggot",
        "faggs",
        "fagot",
        "fagots",
        "fags",
        "fannyflaps",
        "fannyfucker",
        "fanyy",
        "fatass",
        "fcuk",
        "fcuker",
        "fcuking",
        "fingerfuck",
        "fingerfucked",
        "fingerfucker",
        "fingerfuckers",
        "fingerfucking",
        "fingerfucks",
        "fistfuck",
        "fistfucked",
        "fistfucker",
        "fistfuckers",
        "fistfucking",
        "fistfuckings",
        "fistfucks",
        "fuck",
        "fucka",
        "fucked",
        "fucker",
        "fuckers",
        "fuckhead",
        "fuckheads",
        "fuckin",
        "fucking",
        "fuckings",
        "fuckingshitmotherfucker",
        "fuckme",
        "fucks",
        "fuckwhit",
        "fuckwit",
        "fudgepacker",
        "fux0r",
        "f_u_c_k",
        "gangbang",
        "gangbanged",
        "gangbangs",
        "gaysex",
        "god-dam",
        "god-damned",
        "goddamn",
        "goddamned",
        "hardcoresex",
        "horniest",
        "hotsex",
        "jack-off",
        "jackoff",
        "masterbate",
        "masterbation",
        "masterbations",
        "masturbate",
        "mo-fo",
        "mof0",
        "mothafuck",
        "nigger",
        "n1gga",
        "n1gger",
        "nazi",
        "numbnuts",
        "nutsack",
        "orgasim",
        "orgasims",
        "p0rn",
        "penis",
        "penisfucker",
        "phonesex",
        "pigfucker",
        "pussy",
        "pussys",
        "retard",
        "rimming",
        "shit",
        "skank",
        "slut",
        "sluts",
        "s_h_i_t",
        "t1tt1e5",
        "t1tties",
        "testical",
        "testicle",
        "twat",
        "vagina",
        "whore"]

  #NAME_REGEX = /^(?=.{2,20}$)[A-Za-z0-9]+(?:[ _-][A-Za-z0-9]+)*$/
  #HOMETOWN_REGEX = /^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$/u
  #Below is a list of curse words taken from GOOGLE'S banned words list!


  validates :blog_url, :allow_nil => true, :url => {:no_local => true}
  validates :name, :presence => true, :length => { :minimum => 2, :maximum => 20}, exclusion: { in: FORBIDDEN_USERNAMES }
  validates :hometown, :allow_nil => true, :length => { :minimum => 1, :maximum => 100}
  validates :country,  :allow_nil => true, :length => { :minimum => 2, :maximum => 50}
  #validates :hometown, :presence => true, :allow_nil => true, :length => { :minimum => 1, :maximum => 100}, :format => HOMETOWN_REGEX, :confirmation => true
  #validates :country, :presence => true, :allow_nil => true, :length => { :minimum => 2, :maximum => 50}, :format => HOMETOWN_REGEX, :confirmation => true


=begin
  Items for User:
  -Name (letters number and spaces, max 20 characters) *
  -Email (max 50)
  -Password (max 75)
  -Hometown (unicode characters, max 100) *
  -Country (max 5o)
  -Blog (url validator, max 100, post-url crawler) *
  -Profile Picture path (valid path, max 100) *
  -profile url (letters & characters, max-50, url safe on create) *
=end


end

